"""Initial migration.

Revision ID: febe105adffe
Revises: 
Create Date: 2025-01-14 11:52:50.937465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febe105adffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Buses',
    sa.Column('busID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('busName', sa.String(length=50), nullable=False),
    sa.Column('busType', sa.Enum('AC Sleeper', 'Non-AC Seater', 'AC Seater', 'Luxury'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('registrationNumber', sa.String(length=20), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('busID'),
    sa.UniqueConstraint('registrationNumber')
    )
    op.create_table('Routes',
    sa.Column('routeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('estimatedDuration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('routeID')
    )
    op.create_table('Users',
    sa.Column('userID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phoneNumber', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('dateOfBirth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', 'male', 'female', 'other'), nullable=True),  # Updated ENUM
    sa.Column('profilePicture', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Schedules',
    sa.Column('scheduleID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('busID', sa.Integer(), nullable=False),
    sa.Column('routeID', sa.Integer(), nullable=False),
    sa.Column('departureTime', sa.DateTime(), nullable=False),
    sa.Column('arrivalTime', sa.DateTime(), nullable=False),
    sa.Column('fare', sa.Float(), nullable=False),
    sa.Column('daysOfOperation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['busID'], ['Buses.busID'], ),
    sa.ForeignKeyConstraint(['routeID'], ['Routes.routeID'], ),
    sa.PrimaryKeyConstraint('scheduleID')
    )
    op.create_table('SeatLayout',
    sa.Column('seatLayoutID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('busID', sa.Integer(), nullable=False),
    sa.Column('seatMap', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['busID'], ['Buses.busID'], ),
    sa.PrimaryKeyConstraint('seatLayoutID'),
    sa.UniqueConstraint('busID')
    )
    op.create_table('Bookings',
    sa.Column('bookingID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('scheduleID', sa.Integer(), nullable=False),
    sa.Column('seatNumbers', sa.Text(), nullable=True),
    sa.Column('bookingDate', sa.DateTime(), nullable=True),
    sa.Column('totalPrice', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('Confirmed', 'Cancelled', 'Pending', 'Completed'), nullable=True),
    sa.Column('paymentStatus', sa.Enum('Paid', 'Unpaid'), nullable=True),
    sa.Column('paymentGateway', sa.String(length=50), nullable=True),
    sa.Column('transactionID', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['scheduleID'], ['Schedules.scheduleID'], ),
    sa.ForeignKeyConstraint(['userID'], ['Users.userID'], ),
    sa.PrimaryKeyConstraint('bookingID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Bookings')
    op.drop_table('SeatLayout')
    op.drop_table('Schedules')
    op.drop_table('Users')
    op.drop_table('Routes')
    op.drop_table('Buses')
    # ### end Alembic commands ###
