"""Fix backref name conflict

Revision ID: 229a8a5a1562
Revises: 451af3d50e03
Create Date: 2025-02-01 18:36:50.723373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229a8a5a1562'
down_revision = '451af3d50e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Bookings', schema=None) as batch_op:
        batch_op.alter_column('seatNumbers',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)

    with op.batch_alter_table('Buses', schema=None) as batch_op:
        batch_op.alter_column('registrationNumber',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Buses', schema=None) as batch_op:
        batch_op.alter_column('registrationNumber',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('Bookings', schema=None) as batch_op:
        batch_op.alter_column('seatNumbers',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
