"""Add role column to Users table

Revision ID: 276f86524ccb
Revises: c51bfe6e876c
Create Date: 2025-01-28 11:34:36.635884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276f86524ccb'
down_revision = 'c51bfe6e876c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('dateOfBirth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateOfBirth', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
