"""Add dateOfBirth column to Users table

Revision ID: 384bd2f8570b
Revises: 276f86524ccb
Create Date: 2025-01-28 11:41:49.971933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384bd2f8570b'
down_revision = '276f86524ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateOfBirth', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('dateOfBirth')

    # ### end Alembic commands ###
